### ISSUE TITLE
error is coming

### ISSUE THREAD

**Issue by flik** [regniblod/node-mongo-docker-compose#3]
Here is error detail: ```

Removing intermediate container 10037def91dd
 ---> 347b3ec2fda6
Step 4/6 : COPY package.json /app/
ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder823055067/package.json: no such file or directory

```

**Comment by maaixprt** [comment]
package.json is missing in the repo

**Comment by regniblod** [comment]
Closed as there is no more feedback.
